feature/player-interaction
lucasvdiepen/DerailedDeliveries pull request #16
Opened 2024-03-22 13:02 UTC by Joost-Robat

2024-03-25 10:31 UTC, PiterGroot requested changes
Nice stuff

2024-03-25 10:31 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +            if (target.TryGetComponent<Interactable>(out Interactable interactable))
```suggestion
            if (target.TryGetComponent(out Interactable interactable))
```
This is redundant, type can already be retrieved by out keyword

2024-03-25 10:31 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +            if(target.TryGetComponent<Interactable>(out Interactable interactable))
Same thing

2024-03-25 11:55 UTC, lucasvdiepen requested changes

2024-03-25 11:55 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactable.cs
> +        private protected bool IsBeingInteracted { get; set; }
`IsBeingInteracted` is only used and set in `Grabbable` so I think it is better to move it to that script.

2024-03-25 11:55 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactable.cs
> +        /// <param name="interactor">The interactor that his request originates from.</param>
```suggestion
        /// <param name="interactor">The interactor that this request originates from.</param>
```

2024-03-25 11:55 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +            // TO DO: Priority checking for which interactable is most prio.
```suggestion
```

2024-03-25 11:55 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +                interactable.gameObject.transform.localPosition = Vector3.zero;
You can remove this `if` statement and move the line of code after the `SetParent()` line inside the `if` statement.

2024-03-25 11:55 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/PlayerMovement.cs
> +                    Quaternion.Lerp
Maybe we can try using `Slerp` instead of `Lerp`.

2024-03-25 13:09 UTC, PiterGroot approved these changes

2024-03-26 10:47 UTC, lucasvdiepen requested changes

2024-03-26 10:47 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/PlayerMovement.cs
> +            }
Make a new method for this rotation functionality.

2024-03-26 11:26 UTC, Joost-Robat reviewed
Changes of @lucasvdiepen looking good! ;)

2024-03-26 11:53 UTC, lucasvdiepen approved these changes

2024-03-26 11:54 UTC, PiterGroot approved these changes
LGTM

2024-03-26 11:56 UTC, merged