feature/useable-grabbables
lucasvdiepen/DerailedDeliveries pull request #21
Opened 2024-04-02 13:33 UTC by Joost-Robat

Interactable useability and shelf functionality for Grabbables.

2024-04-04 11:51 UTC, lucasvdiepen requested changes

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +        private BoxCollider _boxCollider;
I think the `BoxCollider` may be useful for other interactables aswell. So I would move all the BoxCollider related code to `Interactable.cs`. The `SerializeField` attribute can be removed aswell, since we have a `RequireComponent` attribute.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +                return;
We already have a reference to the `BoxCollider`. So a `TryGetComponent()` is unnecessary.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +            transform.position = hit.point;
In my opinion this is better.
```suggestion
            transform.position = hit.point + new Vector3(0, collider.size.y * .5f, 0);
```

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/UseableGrabbable.cs
> +        private protected virtual Interactable GetInteractable(Interactor interactor)
Maybe rename this method name to `GetCollidingInteractable()` to make it more clear.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/UseableGrabbable.cs
> +    public abstract class UseableGrabbable : Grabbable
Class is missing a summary.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/InteractTargets/ShelfInteractable.cs
Add the `[Server]` attribute to all methods in this script.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactable.cs
> +        public bool InteractAsServer(Interactor interactor) => Interact(interactor);
Add `[Server]` attribute.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactable.cs
> +        public virtual bool Interact(UseableGrabbable useableGrabbable) => false;
Maybe make this summary a bit more clear.

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactable.cs
>  using System;
This using is not used.
```suggestion
```

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +            _inputParser = gameObject.GetComponent<PlayerInputParser>();
```suggestion
            _inputParser = GetComponent<PlayerInputParser>();
```

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +    public class Interactor : NetworkBehaviour
Add `RequireComponent` for `PlayerInputParser` and `SphereCollider`

2024-04-04 11:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Player/Interactor.cs
> +        /// <param name="interactable">The new <see cref="Interactable"/>Target.</param>
```suggestion
        /// <param name="interactable">The new <see cref="Interactable"/> Target.</param>
```

2024-04-04 12:44 UTC, lucasvdiepen requested changes

2024-04-04 12:44 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +        private float _groundCheckDistance = 5f;
```suggestion
        private float _maxGroundDistanceCheck = 5f;
```

2024-04-04 12:44 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +        private Collider[] _collidingInteractables;
I think this variable is not used anymore.

2024-04-04 12:44 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/ShelfInteractable.cs
> +using FishNet.Object.Synchronizing;
```suggestion
using FishNet.Object;
using FishNet.Connection;
using FishNet.Object.Synchronizing;
using UnityEngine;

using DerailedDeliveries.Framework.Gameplay.Player;
using DerailedDeliveries.Framework.Gameplay.Interactions.Grabbables;
```

2024-04-04 12:44 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/ShelfInteractable.cs
> +        }
I think this method can now return true, if this statement: `|| (_heldGrabbable == null && interactor.InteractingTarget != null)` is true. Even if the base call returns false.

2024-04-08 08:33 UTC, lucasvdiepen approved these changes

2024-04-08 08:36 UTC, PiterGroot approved these changes

2024-04-08 08:36 UTC, merged