Feature/damage repair system
lucasvdiepen/DerailedDeliveries pull request #25
Opened 2024-04-10 14:00 UTC by lucasvdiepen

2024-04-11 09:01 UTC, PiterGroot requested changes
Looks very nice.

2024-04-11 09:01 UTC, PiterGroot commented on Assets/Scripts/Framework/DamageRepairManagement/Damageable.cs
> +        private bool _canBeBelowZero;
```suggestion
        private bool _canHaveNegativeHealth;
```

2024-04-11 09:01 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/ShelfInteractable.cs
> +        private void OnHealthChanged(int health)
```suggestion
        private void OnHealthChanged(int health)
               => _heldGrabbableDamageable.CanTakeDamage = health <= 0;
```

2024-04-11 11:27 UTC, Joost-Robat reviewed
Looks good.

2024-04-11 12:13 UTC, PiterGroot approved these changes

2024-04-11 13:12 UTC, Joost-Robat approved these changes
Looks good, ready for merge IMO.

2024-04-12 11:45 UTC, Joost-Robat approved these changes
Looks good, ready for merge.

2024-04-12 11:45 UTC, merged