Feature/vehicle base
lucasvdiepen/DerailedDeliveries pull request #28
Opened 2024-04-12 11:50 UTC by JoepEilander

2024-04-16 10:21 UTC, lucasvdiepen requested changes
The wheelbase is not correctly parented to the train cabins.

2024-04-16 11:48 UTC, lucasvdiepen approved these changes

2024-04-16 12:13 UTC, TryFox requested changes
Connection part still does not look quite right. Maybe try adding half of the extrusion to both sides? We could also look into parenting objects

2024-04-16 12:13 UTC, TryFox commented on Assets/Art/2D/Sprites/S_TrainWheelBig.png
Add this file to a new folder inside `Sprites` for example `Train`

2024-04-16 12:13 UTC, TryFox commented on Assets/Art/2D/Sprites/S_TrainWheelSmall.png
Add this file to a new folder inside `Sprites` for example `Train`

2024-04-16 12:13 UTC, TryFox commented on Assets/Art/Materials/Train/M_TrainBase.mat
Maybe instead of making a new material, use a black spot on another material for the underside

2024-04-16 12:30 UTC, TryFox commented on Assets/Art/Materials/Train/M_TrainBase.mat
Resolved

2024-04-16 12:37 UTC, TryFox requested changes
Same thing as last time, try adding half of the extrusion to both sides. We could also look into parenting objects (sorry for the confusion)

2024-04-16 13:15 UTC, TryFox approved these changes
All changes have been approved

2024-04-16 13:29 UTC, TryFox requested changes
There is a scaling issue in the modles, this is an exporting issue. Please fix

2024-04-17 10:33 UTC, TryFox approved these changes

2024-04-17 10:35 UTC, merged