commit new side cabin
lucasvdiepen/DerailedDeliveries pull request #29
Opened 2024-04-12 12:16 UTC by JoepEilander

2024-04-19 11:59 UTC, lucasvdiepen commented on Assets/Art/2D/Textures/Train/T_TrainSideCabin.png
Is it really necessary to increase the texture size?

2024-05-06 09:41 UTC, TryFox reviewed
All files have been approved. It would be nice if the doors would not ben the same colour as the walls, so they stand out more

2024-05-06 09:56 UTC, TryFox approved these changes
Approved changes

2024-05-06 10:06 UTC, lucasvdiepen requested changes
Colliders are removed from the train side cabin

2024-05-08 09:04 UTC, lucasvdiepen approved these changes

2024-05-08 09:05 UTC, lucasvdiepen approved these changes

2024-05-08 09:30 UTC, Feetjexx approved these changes
Approved

2024-05-08 09:31 UTC, merged