feature/map
lucasvdiepen/DerailedDeliveries pull request #36
Opened 2024-04-18 11:22 UTC by Joost-Robat

2024-04-18 11:37 UTC, PiterGroot requested changes
Only need to check the map popup prefab, good stuff!

2024-04-18 11:37 UTC, PiterGroot commented on Assets/Prefabs/Popup/Map/TestMapPopup.prefab
Please apply `_trackingTransform` to the prefab, it's missing.

2024-04-18 11:43 UTC, Joost-Robat commented on Assets/Prefabs/Popup/Map/TestMapPopup.prefab
Applied!

2024-04-19 09:28 UTC, lucasvdiepen requested changes
The bottom right transform is not applied to the environment prefab.

2024-04-19 09:28 UTC, lucasvdiepen commented on Assets/Art/2D/Sprites/Temp/S_MapPlaceHolder.JPG
Placeholder is one word. Also change the `.JPG` to lowercase.

2024-04-19 09:28 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapUpdater.cs
> +        private Transform _bottomRightWorld;
```suggestion
        private Transform _bottomRightWorldTransform;
```

2024-04-19 09:28 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapUpdater.cs
> +    public class MapUpdater : MonoBehaviour
Add `[RequireComponent]` for `RectTransform`.

2024-05-23 11:57 UTC, PiterGroot requested changes
Good stuff.

2024-05-23 11:57 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/Map/MapManager.cs
> +            return Vector3.Lerp
```suggestion
            return Vector3.Lerp (currentPos, endPos, lerpAlpha);
```

2024-05-23 11:57 UTC, PiterGroot commented on Assets/Scripts/Framework/Gameplay/Level/TrainStation.cs
> +using System;
Move up a bit

2024-05-23 11:57 UTC, PiterGroot commented on Assets/Art/2D/Sprites/Temp/S_MapPlaceHolder.JPG
This can be deleted

2024-05-23 12:49 UTC, lucasvdiepen requested changes

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Art/2D/Sprites/Temp.meta
Folder can be removed.

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Art/2D/Textures/Train/Interior/T_Table.png
Missing suffix.

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapManager.cs
> +        private void UpdateTrackID(int newTrackID, bool isBadRailsplit = false)
```suggestion
        private void UpdateTrackID(int newTrackID, bool isBadRailSplit = false)
```

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapTrack.cs
> +        public int TrackID = -1;
```suggestion
        public int trackID = -1;
```

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapTrack.cs
> +        public SpriteRenderer _badSplitWarning;
```suggestion
        public SpriteRenderer badSplitWarning;
```

2024-05-23 12:49 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Map/MapTrack.cs
> +        public RectTransform[] MapPath;
```suggestion
        public RectTransform[] mapPath;
```

2024-05-23 14:07 UTC, PiterGroot approved these changes

2024-05-24 08:20 UTC, lucasvdiepen approved these changes

2024-05-24 08:29 UTC, merged