Feature/front cabin
lucasvdiepen/DerailedDeliveries pull request #37
Opened 2024-04-19 11:17 UTC by JoepEilander

2024-04-19 12:07 UTC, lucasvdiepen requested changes
There is a weird gap between the front and the coupling piece.
![image](https://github.com/lucasvdiepen/DerailedDeliveries/assets/49072755/4d69985e-b37f-4311-889e-e682aedd5e84)

2024-04-23 12:33 UTC, lucasvdiepen approved these changes

2024-04-23 12:39 UTC, Feetjexx reviewed
Approved

2024-04-23 12:40 UTC, Feetjexx approved these changes
Approved

2024-04-23 12:40 UTC, merged