Feature/character ainimation
lucasvdiepen/DerailedDeliveries pull request #42
Opened 2024-04-23 09:12 UTC by TryFox

Added animations to the scene and made transitions between them.
Still have to fix player color errors

2024-04-23 11:44 UTC, lucasvdiepen requested changes

2024-04-23 11:44 UTC, lucasvdiepen commented on Assets/Art/3D/Controllers/AC_MainCharacter.controller
I think the folder name `Controllers` is a bit too unclear.

2024-04-23 12:39 UTC, Feetjexx approved these changes
Approved

2024-04-24 09:40 UTC, lucasvdiepen approved these changes

2024-04-24 10:31 UTC, PiterGroot approved these changes
Good stuff.

2024-04-24 10:31 UTC, merged