Feature/oven
lucasvdiepen/DerailedDeliveries pull request #45
Opened 2024-04-24 10:36 UTC by Feetjexx

Added new oven mesh to `oven`  folder and into the oven prefab

2024-04-24 10:50 UTC, TryFox reviewed
I think the scale of the oven is a bit to small, please look into that

2024-04-24 12:01 UTC, TryFox requested changes
Never push develop changes unless you have to change something in the settings

2024-04-24 12:01 UTC, TryFox commented on Assets/Scenes/Develop.unity
Don't push develop changes

2024-04-24 12:13 UTC, TryFox reviewed
Position issue has been fixed, still have to fix the scaling issue

2024-05-08 09:41 UTC, TryFox approved these changes

2024-05-08 09:45 UTC, TryFox commented on Assets/Prefabs/Train/TrainController/Train.prefab
look into if this change is needed

2024-05-08 09:56 UTC, lucasvdiepen commented on Assets/Prefabs/Train/TrainController/Train.prefab
Change is for the position of the oven in the train, so this is correct.

2024-05-08 09:56 UTC, lucasvdiepen approved these changes

2024-05-08 09:56 UTC, merged