Feature/environment texture
lucasvdiepen/DerailedDeliveries pull request #48
Opened 2024-04-25 07:33 UTC by angrysnails

Added environment textures

2024-04-25 08:15 UTC, TryFox requested changes
The base color has a _D suffix, please add that to all the base color textures

2024-04-25 08:15 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_GrassNormalMap.png
Normal map has a _N suffix that is missing here

2024-04-25 08:15 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_SnowNormalMap.png
Normal map has a _N suffix that is missing here

2024-04-25 08:56 UTC, TryFox requested changes
Please change naming of Normal map texture

2024-04-25 08:56 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_GrassNormalMap_N.png
dont have to add normal map to the name

2024-04-25 08:56 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_GrassNormalMap_N.png.meta
dont have to add normal map to the name

2024-04-25 08:56 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_SnowNormalMap_N.png
dont have to add normal map to the name

2024-04-25 08:56 UTC, TryFox commented on Assets/Art/2D/Textures/Terrain/T_SnowNormalMap_N.png.meta
dont have to add normal map to the name

2024-04-25 09:01 UTC, TryFox approved these changes

2024-05-08 09:40 UTC, lucasvdiepen requested changes

2024-05-08 09:40 UTC, lucasvdiepen commented on Assets/Terrain/Settings/Pallets/PL_RailGras.terrainlayer
Change name `Gras` to `Grass`.

2024-05-08 09:40 UTC, lucasvdiepen commented on Assets/Art/2D/Textures/Terrain/T_RailGras_D.png
Change name `Gras` to `Grass`.

2024-05-08 09:40 UTC, lucasvdiepen commented on Assets/Terrain/Settings/Pallets/PL_SnowGras.terrainlayer
Change name `Gras` to `Grass`.

2024-05-08 09:40 UTC, lucasvdiepen commented on Assets/Terrain/Settings/Pallets/TP_TerrainPallet.asset
`Pallette Layers` has a missing reference.

2024-05-08 09:55 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not removed | `Assets/Art/2D/UI/Map.meta` |

2024-05-14 07:55 UTC, lucasvdiepen approved these changes

2024-05-14 08:07 UTC, merged