Feature/multiple characters
lucasvdiepen/DerailedDeliveries pull request #49
Opened 2024-04-25 08:37 UTC by JoepEilander

added 6 playable character models and textures

2024-05-06 09:54 UTC, TryFox requested changes
Please fix the issue with the idle animation not working

2024-05-06 13:20 UTC, TryFox approved these changes
Everything works now. Approved all changes

2024-05-08 13:49 UTC, lucasvdiepen requested changes
A lot of texture files are missing a suffix.

2024-05-14 07:48 UTC, lucasvdiepen approved these changes

2024-05-14 07:55 UTC, Feetjexx approved these changes
Approved

2024-05-14 08:31 UTC, PiterGroot requested changes
Nice work. All players are white, maybe because of the texture renaming.

2024-05-14 08:31 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
> +        private GameObject GetAndRemoveRandomPlayerPrefab()
```suggestion
        [Server]
        private GameObject GetAndRemoveRandomPlayerPrefab()
```

2024-05-14 08:31 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
>              ServerManager.Despawn(networkObject);
Make one liner

2024-05-14 08:31 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
> +            _availablePlayerPrefabs.RemoveAt(randomIndex);
```suggestion

            _availablePlayerPrefabs.RemoveAt(randomIndex);
```

2024-05-14 11:51 UTC, PiterGroot approved these changes

2024-05-14 11:51 UTC, merged