Feature/train-doors
lucasvdiepen/DerailedDeliveries pull request #58
Opened 2024-05-06 13:13 UTC by PiterGroot

2024-05-07 07:46 UTC, PiterGroot commented on Assets/Scripts/Framework/Train/TrainStationController.cs
> +                OnParkStateChanged?.Invoke(value);
This ended up being a bit more clear.

2024-05-07 08:33 UTC, Joost-Robat requested changes
Only thing worthy of note is that there was an asset not abiding asset naming conventions but overall looks good!

2024-05-07 08:33 UTC, Joost-Robat commented on Assets/Animations/Train/Doors/TrainSideCabinParent.controller
Please rename file to contain prefix AC_ for animation controller.

2024-05-08 10:24 UTC, lucasvdiepen requested changes
- The doors still need to be seperated in the model.
- Use box colliders on the doors. The player can glitch through mesh colliders sometimes.
- The doors only work on the first cabin.

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainDoorsAnimator.cs
> +        private void OnDisable() => TrainStationController.Instance.OnParkStateChanged -= HandleParkStateChanged;
```suggestion
        private void OnEnable() => TrainStationController.Instance.OnParkStateChanged += HandleParkStateChanged;
        
        private void OnDisable() => TrainStationController.Instance.OnParkStateChanged -= HandleParkStateChanged;
```

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainDoorsAnimator.cs
> +        private int _doorsCloseHash;
```suggestion
        private int _doorsOpenAnimationHash;
        private int _doorsCloseAnimationHash;
```

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainStationController.cs
> +                OnParkStateChanged?.Invoke(value);
Yes, I agree.

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainStationController.cs
> +
This is not used.
```suggestion
```

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainStationController.cs
> +        public Action<bool> OnParkStateChanged { get; set; }
Actions do not need a getter or a setter. Didn't notice it when it was merged.

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/UI/DoorStateUpdater/DoorStateTextUpdater.cs
You don't have to do it for this one, since it is a placeholder, but for next time you can use a `TextUpdater` to update only a part of the text.

2024-05-08 10:24 UTC, lucasvdiepen commented on Assets/Scripts/Framework/UI/DoorStateUpdater/DoorStateTextUpdater.cs
> +        private void OnDisable() => TrainStationController.Instance.OnParkStateChanged -= HandleParkStateChanged;
```suggestion
        private void OnEnable() => TrainStationController.Instance.OnParkStateChanged += HandleParkStateChanged;
        
        private void OnDisable() => TrainStationController.Instance.OnParkStateChanged -= HandleParkStateChanged;
```

2024-05-08 11:09 UTC, PiterGroot commented on Assets/Scripts/Framework/UI/DoorStateUpdater/DoorStateTextUpdater.cs
Ok I didn't know we had a script for updating text. The userstory had a comment saying a UI indicator was needed.  So do you want me to remove this or keep it untill the icons are actually implemented?

2024-05-08 11:11 UTC, PiterGroot commented
> * The doors still need to be seperated in the model.

Yea I was waiting for the new side cabin to be merged, looks like it has been merged now. I will update from develop

2024-05-08 13:51 UTC, lucasvdiepen commented on Assets/Scripts/Framework/UI/DoorStateUpdater/DoorStateTextUpdater.cs
Keep it until the icons are ready.

2024-05-13 09:05 UTC, lucasvdiepen requested changes

2024-05-13 09:05 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainDoorsAnimator.cs
> +        private void Awake() => _doorAnimators = GetComponentsInChildren<Animator>();
I think it is better to keep this script on the same object as the animator. If we use this approach with `GetComponentsInChildren` we will get errors when adding other animators on the train.

2024-05-13 10:33 UTC, lucasvdiepen requested changes

2024-05-13 10:33 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainDoorsAnimator.cs
> +    public class TrainDoorsAnimator : MonoBehaviour
```suggestion
    public class TrainDoorAnimator : MonoBehaviour
```

2024-05-13 10:39 UTC, PiterGroot commented
TODO: apply door animator scripts to sidecabin

2024-05-13 13:06 UTC, PiterGroot commented on Assets/Scripts/Framework/Train/TrainDoorsAnimator.cs
> +    public class TrainDoorsAnimator : MonoBehaviour
Resolved

2024-05-16 10:11 UTC, lucasvdiepen approved these changes

2024-05-16 10:12 UTC, merged