feature/train-steam
lucasvdiepen/DerailedDeliveries pull request #61
Opened 2024-05-07 12:30 UTC by JoepEilander

2024-05-08 11:15 UTC, lucasvdiepen requested changes

2024-05-08 11:15 UTC, lucasvdiepen commented on Assets/Art/2D/Sprites/Train/SH_Steam_512x512.png
Remove `512x512` in name.

2024-05-08 11:15 UTC, lucasvdiepen commented on Assets/Prefabs/Train/TrainController/Steam_ParticleSystem.prefab
Change name to `SteamParticleEffect`.

2024-05-08 11:15 UTC, lucasvdiepen commented on Assets/Prefabs/Train/TrainController/Train.prefab
Changes should have been applied to the front cabin prefab.

2024-05-13 10:03 UTC, Feetjexx approved these changes
Approved

2024-05-14 08:40 UTC, PiterGroot approved these changes

2024-05-14 12:02 UTC, lucasvdiepen approved these changes

2024-05-14 12:06 UTC, merged