Feature/host join screen
lucasvdiepen/DerailedDeliveries pull request #62
Opened 2024-05-07 13:24 UTC by lucasvdiepen

2024-05-08 12:38 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not removed | `Assets/Art/2D/UI/Map 2.meta` |
| Not removed | `Assets/Art/2D/UI/Map.meta` |

2024-05-08 13:28 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not removed | `Assets/Art/2D/UI/Map 2.meta` |
| Not removed | `Assets/Art/2D/UI/Map.meta` |

2024-05-13 07:41 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |
| Not committed | `Assets/Art/2D/UI/JoinScreen.meta` |

2024-05-13 08:07 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |

2024-05-13 10:54 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |

2024-05-13 11:01 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |

2024-05-13 11:05 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |

2024-05-13 11:06 UTC, lucasvdiepen commented
Some missing or dangling .meta found. Fix commits are needed.

| Status | File |
|:--|:--|
| Not committed | `Assets/Art/2D/UI/Hostscreen.meta` |

2024-05-14 08:10 UTC, PiterGroot requested changes
Good stuff, don't forget to update from develop.

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Plugins/Fish-Networking-Discovery/NetworkDiscoveryHud.cs
We dont need this network discovery HUD example file, can you remove it?

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/Buttons/MainMenu/QuitButton.cs
> +    /// A <see cref="BasicButton"/> class which is responsible for closing the application.
```suggestion
    /// A <see cref="BasicButton"/> class responsible for closing the application.
```
To make the summaries a bit more consistent

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/GameManagement/GameManager.cs
> +    /// A class that is responsible for managing the game.
```suggestion
    /// A class responsible for managing the game.
```
for consistency

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
> +        public int MaxPlayers => _maxPlayers;
Change this to an auto getter, setter and serialize its field.

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
> +        private List<Transform> _availableSpawnpoints;
```suggestion
        
        private List<Transform> _availableSpawnpoints;
```

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
>          private bool _isSpawnEnabled;
```suggestion
        
        private bool _isSpawnEnabled;
```

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
>          private int _playerIdCount;
```suggestion
        
        private int _playerIdCount;
```

2024-05-14 08:10 UTC, PiterGroot commented on Assets/Scripts/Framework/StateMachine/StateMachine.cs
> +        /// Invoked when all states are initialized and the state machine is ready.
```suggestion
        /// Called when all states are initialized and the state machine is ready.
```

2024-05-14 08:12 UTC, lucasvdiepen commented on Assets/Plugins/Fish-Networking-Discovery/NetworkDiscoveryHud.cs
Resolved

2024-05-14 12:56 UTC, PiterGroot approved these changes

2024-05-14 13:01 UTC, merged