Feature/rail-split-implementation
lucasvdiepen/DerailedDeliveries pull request #63
Opened 2024-05-08 10:03 UTC by PiterGroot

2024-05-17 08:05 UTC, Joost-Robat reviewed
Looks good, minor comments.

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Scenes/Develop.unity
Don't forget to revert the changes of the Engine health and the Ignore coal burn bool on the Oven.

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Prefabs/Train/Tracks/TrainTracks.prefab
Perhaps change this to TrainTracksPart1 to be more clear.

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Prefabs/Train/Tracks/TrainTracks1.prefab
Perhaps change this to TrainTracksPart2 to be more clear.

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Prefabs/Train/Tracks/TrainTracks2.prefab
Perhaps change this to TrainTracksPart3 to be more clear.

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Scripts/Framework/DamageRepairManagement/Damageables/BoxDamageable.cs
> +
```suggestion
```

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +        private float _damageInterval;
```suggestion
        [SerializeField]
        private float _damageInterval;

        private TrainController _trainController;
```

2024-05-17 08:05 UTC, Joost-Robat commented on Assets/Scripts/Framework/Train/TrainController.cs
> +                }
```suggestion
                else
                    IsOnBadRailSplit = false;
```

2024-05-17 10:54 UTC, lucasvdiepen requested changes

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Camera/CameraShaker.cs
> +                => _multiChannelPerlin.m_FrequencyGain = x, newCameraFrequency, 1);
Should the `1` be a `SerializeField`?

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/DamageRepairManagement/Damageables/BoxDamageable.cs
> +        public void ForceTakeDamage() => TakeDamage();
You can also just make `TakeDamage()` public.

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +        private TrainController _trainController;
Move a bit down.

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +        private BoxDamageable[] boxDamageablesInTrain;
```suggestion
        private BoxDamageable[] _boxDamageablesInTrain;
```

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +        private void Awake() => _trainController = gameObject.GetComponent<TrainController>();
```suggestion
        private void Awake() => _trainController = GetComponent<TrainController>();
```

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +        private void HandleRailSplitChanged(bool badSplit)
```suggestion
        private void HandleRailSplitChanged(bool isBadSplit)
```

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/BadRailSplitDamager.cs
> +                .Where(boxDamageable => boxDamageable.IsInTrain).ToArray();
You can just get all TrainDamageables and damage them. This way the shelf also gets damage.

2024-05-17 10:54 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Train/TrainController.cs
> +        public Action<bool> onRailSplitChange;
```suggestion
        public Action<bool> OnRailSplitChange;
```

2024-05-17 11:55 UTC, PiterGroot commented on Assets/Scripts/Framework/Train/TrainController.cs
> +                }
If either the if or the else in the statement contains multiple lines both the if and the else need brackets.  Here in the [code convention](https://github.com/lucasvdiepen/DerailedDeliveries/wiki/Code-Conventions#if-statements).

2024-05-21 08:39 UTC, Joost-Robat commented on Assets/Scripts/Framework/Train/TrainController.cs
> +                }
You are correct, I wasn't paying attention!

2024-05-23 07:10 UTC, Joost-Robat reviewed
Looks good, when updated with develop has to be checked again though.

2024-05-23 08:47 UTC, Joost-Robat approved these changes
Looks good, works good, very good! Ready for merge.

2024-05-23 09:04 UTC, lucasvdiepen requested changes

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Art/2D/Textures/Environment/T_SplitsingLeft.png
`Splitsing` should be translated to english. It is also missing a suffix.

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Art/2D/Textures/Environment/T_SplitsingRight.png
`Splitsing` should be translated to english. It is also missing a suffix.

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Art/Materials/Environment/M_SplitsingLeft.mat
`Splitsing` should be translated to english.

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Art/Materials/Environment/M_SplitsingRight.mat
`Splitsing` should be translated to english.

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Scripts/Framework/DamageRepairManagement/Damageable.cs
> +        public virtual void TakeDamage()
This needs a summary now that it is public.

2024-05-23 09:04 UTC, lucasvdiepen commented on Assets/Scripts/Framework/DamageRepairManagement/Damageables/BoxDamageable.cs
> +        public override void TakeDamage()
This is missing a summary but can use `<inheritdoc>`.

2024-05-23 09:15 UTC, lucasvdiepen approved these changes

2024-05-23 09:21 UTC, merged