Feature/audio-system
lucasvdiepen/DerailedDeliveries pull request #84
Opened 2024-05-20 14:20 UTC by PiterGroot

2024-05-23 10:16 UTC, PiterGroot commented
TODO: Add coal oven toggle state sound

2024-05-24 06:37 UTC, lucasvdiepen requested changes

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/CoalOvenSystem/CoalOven.cs
> +        [ObserversRpc(RunLocally = true, BufferLast = true)]
`BufferLast` can be removed.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/CoalOvenSystem/CoalOven.cs
> +        private void PlayOvenSound(bool ovenEnabled)
```suggestion
        private void PlayOvenSound(bool isOvenEnabled)
```

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/DamageRepairManagement/TrainDamageable.cs
> +        [ObserversRpc(RunLocally = true, BufferLast = true)]
`BufferLast` can be removed.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +        }
You can just have 1 `PlayGrabbableSound()` call above the ObjectParent if statement.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Grabbables/Grabbable.cs
> +        [ObserversRpc(RunLocally = true, BufferLast = true)]
`BufferLast` can be removed.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/CoalOvenInteractable.cs
> +        [ObserversRpc(RunLocally = true, BufferLast = true)]
`BufferLast` can be removed.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/TrainSpeedButtonInteractable.cs
> +using FishNet.Object;
Move up a bit.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/Gameplay/Interactions/Interactables/TrainSpeedButtonInteractable.cs
> +        [ObserversRpc(RunLocally = true, BufferLast = true)]
`BufferLast` can be removed.

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/UI/TextUpdaters/Lobby/PlayerListTextUpdater.cs
> +using DerailedDeliveries.Framework.Audio;
```suggestion
```

2024-05-24 06:37 UTC, lucasvdiepen commented on Assets/Scripts/Framework/PlayerManagement/PlayerManager.cs
> +                AudioSystem.Instance.PlayRandomSoundEffectOfType(AudioCollectionTypes.PlayerJoined);
This is only called on the server. Maybe move it to `PlayerJoined`. That method runs on all clients.

2024-05-24 08:08 UTC, lucasvdiepen approved these changes

2024-05-24 08:22 UTC, lucasvdiepen approved these changes

2024-05-24 08:40 UTC, merged