feature/shaders
lucasvdiepen/DerailedDeliveries pull request #93
Opened 2024-05-23 07:44 UTC by Feetjexx

Added shaders to almost all materials

2024-05-23 08:11 UTC, JoepEilander approved these changes

2024-05-23 09:25 UTC, lucasvdiepen requested changes

2024-05-23 09:25 UTC, lucasvdiepen commented on Assets/Art/Materials/Train/Kolenbak/M_Kolenbak.mat
`Kolenbak` should be translated to english.

2024-05-23 09:25 UTC, lucasvdiepen commented on Assets/Art/Shaders/CiroContinisio/ToonShader.meta
All toon shader related folders can be moved to `ThirdPartyAssets` folder.

2024-05-24 08:26 UTC, lucasvdiepen approved these changes

2024-05-24 08:56 UTC, merged